#!/bin/sh
#
# Clone and then update the git repository in ./workspace

git-pull() {
    REPO="$1"
    echo "[git-pull]"

    if [ -d ./workspace ]; then
        git -C ./workspace pull
    else
        git clone "$1" ./workspace
    fi

}
