#!/bin/sh
#
# Lint all php files in ./workspace/src

php-lint() {
    echo "[php-lint]"

    if [[ ! -d "./workspace/src" ]]; then
        echo "Folder  not found: ./workspace/src"
        exit 1
    fi

    find ./workspace/src -name '*.php' | xargs -n1 php -l
}
