#!/bin/bash
set -eu -o pipefail

bootstrap() {
JOBS=$HOME/.jobs
mkdir -p "$JOBS"

for module in "$ROOT"/modules/*; do
    source "$module"
done

for module in "$ROOT"/contrib/*; do
    source "$module"
done
}

create-job() {
    NAME="$1"

#    if [ -d "$JOBS/$NAME" ]; then
#        echo "Job with name $NAME already exists"
#        exit 1
#    fi

    mkdir "$JOBS/$NAME/"
    mkdir "$JOBS/$NAME/workspace"
    mkdir "$JOBS/$NAME/builds"

    touch "$JOBS/$NAME/build"
}

list-jobs() {
    for job in "$JOBS"/*; do
        basename "$job"
    done
}

delete-job() {
    NAME="$1"

    if [ ! -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME does not exists"
        exit 1
    fi

    rm -rf "$JOBS/$NAME/"
    echo "Deleted job at $JOBS/$NAME"
}

run-job() {
    NAME="$1"

    if [ ! -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME does not exists"
        exit 1
    fi

    # Change current working directory to the job folder
    cd "$JOBS/$NAME"

    # Write to both stdout and file
    LOG="./output.log"
    date '+%Y-%m-%d %H:%M:%S' | tee -a "$LOG"
    source "./build" | tee -a "$LOG"
}

