#!/bin/bash
set -eu -o pipefail

ROOT=$(dirname "$0")/

JOBS=$HOME/me/jobs
mkdir -p "$JOBS"

for module in "$ROOT"/modules/*; do
    source "$module"
done

for module in "$ROOT"/contrib/*; do
    source "$module"
done

create-job() {
    NAME="$1"

    if [ -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME already exists"
        exit 1
    fi

    mkdir "$JOBS/$NAME/"
#    mkdir "$JOBS/$NAME/workspace"
    mkdir "$JOBS/$NAME/builds"
    mkdir "$JOBS/$NAME/config"

    touch "$JOBS/$NAME/job"
    touch "$JOBS/$NAME/job.log"
}

edit-job() {
    NAME="$1"

    if [ ! -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME does not exists"
        exit 1
    fi

    vim "$JOBS/$NAME/job"
}

list-jobs() {
    for job in "$JOBS"/*; do
        basename "$job"
    done
}

delete-job() {
    NAME="$1"

    if [ ! -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME does not exists"
        exit 1
    fi

    rm -rf "$JOBS/$NAME/"
    echo "Deleted job at $JOBS/$NAME"
}

run-job() {
    NAME="$1"

    if [ ! -d "$JOBS/$NAME" ]; then
        echo "Job with name $NAME does not exists"
        exit 1
    fi

    # Change current working directory to the job folder
    cd "$JOBS/$NAME"

    LOG="./job.log"
    HEADER=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$HEADER]" | tee -a "$LOG"
    # Write to stdout and file
    source "./job" 2>&1 | tee -a "$LOG"
    echo "" | tee -a "$LOG"
}

operation="${1-list}"
name="${2-}"

case "$operation" in 

    create)
        create-job "$name"
        ;;

    remove)
        delete-job "$name"
        ;;

    edit)
        edit-job "$name"
        ;;

    list)
        list-jobs
        ;;

    run)
        run-job "$name"
        ;;

    *)
        echo default
        ;;
esac
